### DISCUSSION TITLE
Unable to use project factory yaml within folder hierarchy

### DISCUSSION THREAD

**Discussion by derailed-dash** [GoogleCloudPlatform/cloud-foundation-fabric#2465] [Q&A] [answered]
I've been trying to use the project-factory as described [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/project-factory).

I have created a folder hierarchy, with the structure:
/data/hierarchy/tnt-foo

Within my `tnt-foo` folder, I have a defined a project yaml called prj-foo-app-1.yaml:

```yaml
# project prj-foo-app-1
labels:
 app: app-1
 team: foo
services:
  - container.googleapis.com
  - storage.googleapis.com
service_accounts:
  app-1-be:
    display_name: "Foo app 1 backend."
    iam_self_roles:
    - roles/logging.logWriter
    - roles/monitoring.metricWriter
    iam_project_roles:
      my-host-project:
        - roles/compute.networkUser
  app-1-fe:
    display_name: "Foo app 1 frontend."
    iam_project_roles:
      my-host-project:
        - roles/compute.networkUser
billing_budgets:
  - billing-20
```

When I run my `terraform plan`, the project to be created correctly detects that its parent is `tnt-foo`.  But the Terraform then fails, because the project module expects the parent to always be of the form "folders/folder_id" or "organizations/organization_id".  (See .terraform/modules/project-factory/modules/project-factory/main.tf line 24, in module "projects".)

The examples indicate that it should be possible to specify a parent in this format, e.g.

```yaml
parent: bar/baz
```

Of course, at runtime, the folder ID of the newly created folder is not yet known.  So I need to either determine the newly created folder ID at runtime, or the Terraform needs to work with a parent folder name, rather thn a folder ID.

Please can you help?
