### DISCUSSION TITLE
Not able to add attributes directly for network_subnet_users in project factory

### DISCUSSION THREAD

**Discussion by HarshalSanap007** [GoogleCloudPlatform/cloud-foundation-fabric#2835] [Q&A] [answered]
Hey @ludoo, Im trying to create with project factory in .yaml file we have one field called "network_users" but I wanted it add "network_subnet_users" to grant users access on specific subnets only. 
As like network_users for which we are directly passing the value from .auto.tfvars.json similarly I tried replicating for "network_subnet_users" because I didn't want to pass users or service account explicitly in my .yaml file. but it threw error.
```
parent: team-a/dev
shared_vpc_service_config:
  host_project: dev-spoke-0
  network_users:
    - gcp-devops
```
but when I modified this to 
```
shared_vpc_service_config:
  host_project: dev-spoke-0
  network_subnet_users:
    "australia-southeast1/subnet-name":
    - "group:gcp-devops@company.com"
    "australia-southeast1/subnet-name":
    - "serviceAccount:service-account-email"
    
```
this works perfectly , it adds that user/service account  to the subnet as network user.
but problem arises when , if I try to pass the same gcp-devops group or service account as a attribute from .tfvars.json  to "network_subnet_user"

```
parent: team-a/dev
shared_vpc_service_config:
  host_project: dev-spoke-0
  network_subnet_users:
    "australia-southeast1/subnet-name":
    - gcp-devops // or service account attribute from .tfvars.auto.json
```
Its not accepting this and start throwing error as 

```
Error: invalid value for member (IAM members must have one of the values outlined here: https://cloud.google.com/billing/docs/reference/rest/v1/Policy#Binding)
 with module.projects.module.projects["sample-app-01"].google_compute_subnetwork_iam_member.shared_vpc_host_subnets_iam["australia-southeast1:subnet-name:gcp-devops"],
│   on ../../../modules/project/shared-vpc.tf line 157, in resource "google_compute_subnetwork_iam_member" "shared_vpc_host_subnets_iam":
│  157:   member     = each.value.member

```
Could you please help me ?
thanks
