### DISCUSSION TITLE
Granting compute.networkUser to a service agent in a project created via project factory

### DISCUSSION THREAD

**Discussion by rossiellog** [GoogleCloudPlatform/cloud-foundation-fabric#2945] [Q&A] [answered]
As the title says, I'm trying to find a way to grant roles/compute.networkUser to a service agent (workstations) on the prod net spoke project from stage 2-networking. The project in which the service agent resides has been initialized by the project factory. I have been messing a bit with the iam-related variables in project factory, to no avail. Is there a way to achieve the aforementioned? If so, how? Otherwise, is this something I can do manually only?

**Comment by wiktorn** [comment, marked as answer]
Did you try approach documented in project module [example for Shared VPC](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/project#shared-vpc)?

You need something like:
```yaml
  shared_vpc_service_config:
    host_project: ....
    service_agent_iam:
      "roles/compute.networkUser":
      - workstations
```
