### ISSUE TITLE
net-vpc-firewall when using yaml rule format fails to generate correct rule with source_tags

### ISSUE THREAD

**Issue by hql898** [GoogleCloudPlatform/cloud-foundation-fabric#1058]
When configured GCP firewall rule with source_tags in Yaml format as the following, the net-vpc-firewall module always generate additional source_ranges = [0.0.0.0/0]. Same would also happened even I tried to set source_ranges = [].
Was that something I missed? How do I generate rule (in yaml) with source_tags but without source_ranges?

Thank you

============
Input yaml file with the following rule configuration:

source tag setting is not working; 
always add sourceRanges 0.0.0.0/0 to the rule in addition to the specified sourceTags

```
deny-connector-by-src-tag:
  description: test firewall rule using src tag
  direction: INGRESS
  action: deny
  sources: [vpc-connector]
  targets: []
  use_service_accounts: false
  rules:
    - protocol: all
      ports: null
  extra_attributes:
    disabled: false
    priority: 990
    logging: 'INCLUDE_ALL_METADATA'
```

Describe rule output:

```
user@cloudshell:~$ gcloud compute firewall-rules describe deny-connector-by-src-tag --project project-1-123456
creationTimestamp: '2022-12-19T14:36:47.854-08:00'
denied:
- IPProtocol: all
description: test firewall rule using src tag
direction: INGRESS
disabled: false
id: '2129710410780989840'
kind: compute#firewall
logConfig:
  enable: true
  metadata: INCLUDE_ALL_METADATA
name: deny-connector-by-src-tag
network: https://www.googleapis.com/compute/v1/projects/project-1-123456/global/networks/myvpc
priority: 990
selfLink: https://www.googleapis.com/compute/v1/projects/project-1-123456/global/firewalls/deny-connector-by-src-tag
sourceRanges:
- 0.0.0.0/0
sourceTags:
- vpc-connector
user@cloudshell:~$
```

Terraform apply output:

```
~/Documents/cloud-foundation-fabric-master/xxxx/$terraform apply
google_compute_firewall.rules: Refreshing state... [id=projects/project-1-123456/global/firewalls/test-deny-connector-traffic-by-src-tag]
google_compute_network.vpc_network: Refreshing state... [id=projects/project-1-123456/global/networks/myvpc]
google_compute_subnetwork.mysubnet2: Refreshing state... [id=projects/project-1-123456/regions/us-east5/subnetworks/subnet5]
google_compute_subnetwork.mysubnet1: Refreshing state... [id=projects/project-1-123456/regions/us-central1/subnetworks/subnet1]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # module.firewall-rules.google_compute_firewall.custom-rules["deny-connector-by-src-tag"] will be created
  + resource "google_compute_firewall" "custom-rules" {
      + creation_timestamp = (known after apply)
      + description        = "test firewall rule using src tag"
      + destination_ranges = (known after apply)
      + direction          = "INGRESS"
      + disabled           = false
      + enable_logging     = (known after apply)
      + id                 = (known after apply)
      + name               = "deny-connector-by-src-tag"
      + network            = "myvpc"
      + priority           = 990
      + project            = "project-1-123456"
      + self_link          = (known after apply)
      + source_ranges      = [
          + "0.0.0.0/0",
        ]
      + source_tags        = [
          + "vpc-connector",
        ]

      + deny {
          + ports    = []
          + protocol = "all"
        }

      + log_config {
          + metadata = "INCLUDE_ALL_METADATA"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.firewall-rules.google_compute_firewall.custom-rules["deny-connector-by-src-tag"]: Creating...
module.firewall-rules.google_compute_firewall.custom-rules["deny-connector-by-src-tag"]: Still creating... [10s elapsed]
module.firewall-rules.google_compute_firewall.custom-rules["deny-connector-by-src-tag"]: Creation complete after 12s [id=projects/project-1-123456/global/firewalls/deny-connector-by-src-tag]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

network = "projects/project-1-123456/global/networks/myvpc"
[Mon Dec 19 17:36:56]
~/Documents/cloud-foundation-fabric-master/xxxx/$
```
