### ISSUE TITLE
Cannot connect Composer 2 to Cloud SQL in Shared VPC

### ISSUE THREAD

**Issue by yardenas** [GoogleCloudPlatform/cloud-foundation-fabric#1490]
Hi Everyone!

We follow FAST and brought up our whole organization with it. For networking, we chose the [hub-spoke](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/fast/stages/2-networking-a-peering) architecture. We created a project for our development environment that runs cloud SQL (with private IP, with host project as `dev-spoke-0`) and Composer 2 (following [this guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/data-solutions/composer-2#shared-vpc)). This setup works well---workers from composer are able to successfully connect to Cloud SQL.

For our production environment, we basically do the same. However, since FAST provides only [`dev-dataplatform-ew1.yaml`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/2-networking-a-peering/data/subnets/dev/dev-dataplatform-ew1.yaml) for development, without a corresponding file for production, we copied the development one into the `prod` folder, changing the IP addresses (since we would have a conflict with the ones from development otherwise).
```yaml
region: us-central1
description: Default subnet for dev Data Platform
ip_cidr_range: 172.16.0.0/12
secondary_ip_ranges:
  pods: 10.10.8.0/22
  services: 10.10.12.0/24
```

Now, we deploy Cloud SQL and Composer 2 on our production project, however we are not able to connect Composer's workers to the database. Does anyone have an idea what could go wrong? We're pretty sure it's a networking issue, but have no idea how to debug it.

Any help would be great!
