### ISSUE TITLE
Org Policies list type with Tags

### ISSUE THREAD

**Issue by AurelienBegou** [GoogleCloudPlatform/cloud-foundation-fabric#1493]
Hi,

I'm trying to use Tags to manage Org Policies and I have an issue with the current behaviour and some difficulties to fix it.

The Organisation Policy yaml is the one below, I used "gcloud org-policies set-policy" to set it
```
name: folders/380194406045/policies/compute.vmExternalIpAccess
spec:
  rules:
  - allowAll: true
    condition:
      description: Allow External IP
      expression: resource.matchTag("387792487373/gcp-tag-vm-vmExternalIpAccess", "allow")
      title: Allow External IP
  - condition:
      expression: '!resource.matchTag("387792487373/gcp-tag-vm-vmExternalIpAccess", "allow")'
      title: Deny External IP
    denyAll: true
```

Now I have the yaml to configure the organization module. My issue is that the module will always configure at least one rule.
It tried to change code to be able to configure a condition with the default rule but I didn't achieved to make it work.
```
constraints/compute.vmExternalIpAccess:
  deny: 
    all: true
  condition:
    expression: "!resource.matchTag(\"387792487373/vm_external_ip_access\", \"allow\")"
    title    : "Deny External IP"
    description: "Deny External IP"
    location: ""
  rules:
    - allow: 
        all: true
      condition:
          expression: "resource.matchTag(\"387792487373/vm_external_ip_access\", \"allow\")"
          title    : "Allow External IP"
          description: "Allow External IP"
          location: ""
```

I tried first to configure only rules but the default rule applied return a 400 from Google.
```
constraints/compute.vmExternalIpAccess:
  rules:
   - deny: 
       all: true
      condition:
          expression: "!resource.matchTag(\"387792487373/vm_external_ip_access\", \"allow\")"
          title    : "Deny External IP"
          description: "Deny External IP"
          location: ""
    - allow: 
        all: true
      condition:
          expression: "resource.matchTag(\"387792487373/vm_external_ip_access\", \"allow\")"
          title    : "Allow External IP"
          description: "Allow External IP"
          location: ""
```

My version of Terraform:
```
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.64.0
+ provider registry.terraform.io/hashicorp/google-beta v4.64.0
+ provider registry.terraform.io/hashicorp/random v3.3.2
```

What do you think about it ?
