### ISSUE TITLE
Unable to acquire impersonated credentials

### ISSUE THREAD

**Issue by danielmahon** [GoogleCloudPlatform/cloud-foundation-fabric#1624]
Similar to #1441 GitHub actions fails at "Copy Terraform output files" but on bootstrap as well

Has the permission scheme changed lately? I am getting the same "IAM_PERMISSION_DENIED" error, however, the repo names match (AFAIK). I don't see the same permissions as the other issue though. Steps 0,1, and github extra all completed successfully.

```
ERROR: (gcloud.alpha.storage.cp) There was a problem refreshing your current auth tokens: ('Unable to acquire impersonated credentials', '{\n  "error": {\n    "code": 403,\n    "message": "Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "reason": "IAM_PERMISSION_DENIED",\n        "domain": "iam.googleapis.com",\n        "metadata": {\n          "permission": "iam.serviceAccounts.getAccessToken"\n        }\n      }\n    ]\n  }\n}\n')
```

bootstrap tfvars
```
# use something unique and no longer than 9 characters
prefix = "mahon"

federated_identity_providers = {
  # Use the public GitHub and specify an attribute condition
  github = {
    attribute_condition = "attribute.repository_owner==\"GITHUB_ORG\""
    issuer              = "github"
    custom_settings     = null
  }
}

cicd_repositories = {
  bootstrap = {
    branch            = null
    identity_provider = "github"
    name              = "GITHUB_ORG/fast_00_bootstrap"
    type              = "github"
  }
  resman = {
    branch            = "main"
    identity_provider = "github"
    name              = "GITHUB_ORG/fast_01_resman"
    type              = "github"
  }
}
```

bootstrap workflow
```
env:
  FAST_OUTPUTS_BUCKET: mahon-prod-iac-core-outputs-0
  FAST_SERVICE_ACCOUNT: mahon-prod-bootstrap-1@mahon-prod-iac-core-0.iam.gserviceaccount.com
  FAST_WIF_PROVIDER: projects/REDACT/locations/global/workloadIdentityPools/mahon-bootstrap/providers/mahon-bootstrap-github
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  TF_PROVIDERS_FILE: 0-bootstrap-providers.tf
  TF_VERSION: 1.4.4
```

IAM
It looks like the cicd.tf is only setting LogsWriter and not ServiceAccountTokenCreator, but that seems to follow with the documentation, unlike in the other issue.

![Screenshot 2023-08-26 at 6 38 16 PM](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/1088089/789ece77-dfe4-40a7-9661-0e0e6b3d8061)

Im not sure what should be different here but the "SUBJECT_ATTRIBUTE_VALUE" stands out

![Screenshot 2023-08-26 at 6 40 09 PM](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/assets/1088089/67914b20-70aa-4e8c-a990-03ceef3c02f0)

Let me know if I can provide anything else to help troubleshoot. All the rest of my configuration follows with the documentation. Let me know if I screwed up somewhere 😉
