### ISSUE TITLE
Project factory fail with two+ yaml defined projects

### ISSUE THREAD

**Issue by jackspyder** [GoogleCloudPlatform/cloud-foundation-fabric#1799]
Hello, 

When using the v27.0.0 project factory using yaml defined projects i get the following error:

```
Error: Inconsistent conditional result types
│ 
│   on .terraform/modules/projects/blueprints/factories/project-factory/factory.tf line 21, in locals:
│   19:     var.factory_data.data != null
│   20:     ? var.factory_data.data
│   21:     : {
│   22:       for f in fileset("${local._data_path}", "**/*.yaml") :
│   23:       trimsuffix(f, ".yaml") => yamldecode(file("${local._data_path}/${f}"))
│   24:     }
│     ├────────────────
│     │ local._data_path is "data/projects"
│ 
│ The false result value has the wrong type: element types must all match for conversion to map.
```

I've done some digging around at the fail recent changes around this blueprint/module etc, and i've managed to find an approximate fix, but i'm not quite fully confident in my findings or your thinking to be 100% enough to raise a PR.

It seems in the factory.tf file in the PF blueprint, our _data local is causing an issue here. Weirdly, when my two yaml projects don't create service accounts it works, but when they do define a service account each it breaks.

Switching the factory.tf _data portion from:
```
  _data = (
    var.factory_data.data != null
    ? var.factory_data.data
    : {
      for f in fileset("${local._data_path}", "**/*.yaml") :
      trimsuffix(f, ".yaml") => yamldecode(file("${local._data_path}/${f}"))
    }
  )
```

to a similar example from elsewhere
```
_data =  {
      for f in try(fileset("${local._data_path}", "**/*.yaml"), []) :
      trimsuffix(f, ".yaml") => yamldecode(file("${local._data_path}/${f}"))
    }
```
    
This change resolves my issue and the projects plan/apply as expected. Tests seem to continue to pass too with this change. Hopefully this information is useful, i'll include the two basic yaml files im using to test below if that helps:
   
yaml project 1:
```
# [opt] Labels for the project - merged with the ones defined in defaults
labels:
 team: report-it
 environment: test

# Folder the project will be created as children of
parent: folders/1234567

# [opt] APIs to enable on the project.
services:
- compute.googleapis.com
- storage.googleapis.com

# [opt] Authoritative IAM bindings in group => [roles] format
group_iam:
  redacted-group@customer.com:
    - roles/bigquery.user

# [opt] Authoritative IAM bindings in role => [principals] format
# Generally used to grant roles to service accounts external to the project
# iam:

# iam_bindings:

# iam_bindings_additive:

# [opt] Org policy overrides defined at project level
org_policies:
  iam.disableServiceAccountKeyCreation:
    rules:
    - enforce: false

# [opt] Service account to create for the project and their roles on the project
# in name => [roles] format
service_accounts:
  dev-sa-read: {}
  dev-sa-write: {}
```
  
  and yaml project 2:
```
# [opt] Labels for the project - merged with the ones defined in defaults
labels:
 team: report-it
 environment: test

# Folder the project will be created as children of
parent: folders/1234567

# [opt] APIs to enable on the project.
services:
- compute.googleapis.com
- storage.googleapis.com

# [opt] Authoritative IAM bindings in group => [roles] format
group_iam:
  redacted-group@customer.com:
    - roles/bigquery.user

# [opt] Authoritative IAM bindings in role => [principals] format
# Generally used to grant roles to service accounts external to the project
# iam:

# iam_bindings:

# iam_bindings_additive:

# [opt] Org policy overrides defined at project level
org_policies:
  iam.disableServiceAccountKeyCreation:
    rules:
    - enforce: false

# [opt] Service account to create for the project and their roles on the project
# in name => [roles] format
service_accounts:
  test-sa-read: {}
  test-sa-write: {}
```
