### ISSUE TITLE
Question: Project Factory - configure service project to shared subnet

### ISSUE THREAD

**Issue by jackspyder** [GoogleCloudPlatform/cloud-foundation-fabric#1865]
Hello, 

Sorry if im being a bit thick here, since the various PF changes in the last few versions i'm a little lost as to how in a yaml defined project factory entry i'd now configure a shared subnet from the networking layer.

Previously this was done, and i can't quite figure out the new way.

Thanks

```
vpc:
  host_project: fast-dev-net-spoke-0
  subnets_iam:
    europe-west1/dev-default-ew1:
      - user:foobar@example.com
      - serviceAccount:my-service-account
```

**Comment by ludoo** [comment]
Just mirror the project factory module variable type, but un yaml:

```yaml
shared_vpc_service_config:
    host_project: module.host-project.project_id
    service_identity_iam:
      "roles/compute.networkUser":
        - cloudservices
        - container-engine
```
