### ISSUE TITLE
Examply policy at org-policies/serverless.yaml is broken

### ISSUE THREAD

**Issue by markusl** [GoogleCloudPlatform/cloud-foundation-fabric#2323]
**Describe the bug**

The example provided does not work:
```yaml
constraints/cloudfunctions.restrictAllowedGenerations:
  - allow:
      values:
       - is:2ndGen
```

**Environment**
```
Terraform v1.8.3
```

**Expected behavior**

Provided examples should work :)

**Comment by juliocc** [comment]
It's missing the `rules` field. Can you try this:
```yaml
constraints/cloudfunctions.restrictAllowedGenerations:
  rules:
  - allow:
      values:
      - is:2ndGen
```
