### ISSUE TITLE
[FR]: project factory - automation service accounts, buckets and permissions

### ISSUE THREAD

**Issue by LucaPrete** [GoogleCloudPlatform/cloud-foundation-fabric#3109]
### The feature request

I'm using the latest project factory module from fast-dev.

I need to create a service account and a bucket for automation, contextually with the project and inside the project (I'm creating with PF).

The automation block does not allow to create service account and the bucket in the project that the user is creating. This feature imho would be not necessarily recommended but still desirable by many users.

As an example, this would be for me a valid configuration and would create the service account and the bucket in my project.

```yaml
automation:
  service_accounts:
    rw:
  bucket:
    name: gf-srun-0
    description: Terraform state bucket
    iam:
      roles/storage.objectAdmin:
        - automation/rw
      roles/storage.objectViewer:
        - automation/rw
```

As a work around, I was recommended to leverage the service_accounts and buckets block.
This anyway doesn't work (for the specific use-case), as I'm not able to cross-reference the service account keys in the IAM directives in the same service accounts block. For example, this doesn't work:

```
service_accounts:
  # Automation SAs
  iac-rw:
  # Application SAs
  gf-rrag-fe-0:
    iam:
      roles/iam.serviceAccountUser:
        - iac-rw
  gf-rrag-fe-build-0:
  gf-rrag-ing-0:
    iam:
      roles/iam.serviceAccountUser:
        - iac-rw
  gf-rrag-ing-build-0:
  gf-rrag-ing-sched-0:
    **iam:
      roles/iam.serviceAccountUser:
        - iac-rw**
```

### Proposed solution

It would be very nice to support both cases. In order of (personal) preference I'd choose:
1) automation block creates SAs and buckets in the project if the project is not specified
2) service accounts can reference each other within IAM blocks
